services:
  mongodb:
    image: mongo:7
    container_name: vaseaux_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - vaseaux_mongo_data:/data/db

volumes:
  vaseaux_mongo_data:
