import { demoGallery, img } from "@/lib/seed/helpers";
import { policyListItems, policySectionsBody } from "@/lib/seed/policies";
import type { IPageSection } from "@/models/Page";

const SHARED_AMENITIES = [
  "Private washroom with hot shower, sink, and toilet",
  "Fully stocked kitchen with fridge/freezer, stove/oven, and cookware",
  "Patio with picnic table",
  "Propane BBQ",
];

function homeSections(): IPageSection[] {
  return [
    {
      sectionKey: "hero",
      type: "hero",
      enabled: true,
      order: 0,
      eyebrow: "Vaseaux Lake • South Okanagan",
      heading: "Our guests come for the lake — and stay for the memories.",
      subheading:
        "A classic Okanagan lake vacation — simple, affordable, nostalgic and made for families.",
      ctaText: "Explore the cabins",
      ctaUrl: "/cabins",
      backgroundImage: img("lakeHero", "Sunrise over Vaseaux Lake"),
      foregroundImage: img("historic", "Vintage lakeside postcard frame"),
      images: demoGallery(3, "Homepage hero collage"),
    },
    {
      sectionKey: "inquiry-bar",
      type: "inquiry-bar",
      enabled: true,
      order: 1,
      heading: "Plan your stay",
      subheading: "Share your dates and guest count — we will reply with availability and a quote.",
      ctaText: "Check availability",
      ctaUrl: "/inquire",
    },
    {
      sectionKey: "cabin-truth",
      type: "rich-text",
      enabled: true,
      order: 2,
      eyebrow: "A different kind of cabin stay",
      heading: "Eight private stays under one historic roof",
      body: "Our property is not a collection of detached cabins. Eight private cabin-style accommodations share one nostalgic lakeside building — each with its own space and character, steps from the lawn, beach, and lake.",
      images: demoGallery(2, "Historic building overview"),
      backgroundImage: img("cabinInterior", "Cabin-style unit interior"),
    },
    {
      sectionKey: "cabin-rail",
      type: "cabin-rail",
      enabled: true,
      order: 3,
      heading: "Cabins 5–12",
      subheading: "Compare capacity and sleeping layouts, then inquire for your dates.",
      ctaText: "View all cabins",
      ctaUrl: "/cabins",
    },
    {
      sectionKey: "outside-life",
      type: "image-text",
      enabled: true,
      order: 4,
      eyebrow: "The holiday happens outside",
      heading: "Patios, BBQs, boats, and star-filled skies",
      body: "The heart of a Vaseaux Lake stay is outdoors: lawns and beach, complimentary boats and paddleboards, a floating raft, evening gatherings, and incredible night skies over the water.",
      listItems: [
        "Patios and propane BBQs",
        "Lawn and shallow lake access",
        "Complimentary boats and paddleboards",
        "Floating raft",
        "Evening gatherings and stargazing",
      ],
      images: demoGallery(4, "Outdoor lake life"),
      backgroundImage: img("patioBbq", "Patio and BBQ by the lake"),
      foregroundImage: img("boats", "Boats on Vaseaux Lake"),
    },
    {
      sectionKey: "history-preview",
      type: "timeline",
      enabled: true,
      order: 5,
      eyebrow: "Since the 1960s",
      heading: "From the Sundial Motel to summers remembered",
      body: "Originally opened as the Sundial Motel in the 1960s, the property has welcomed generations of visitors. Step inside and you may find a little taste of the 1970s — when summer meant lakeside days and family time.",
      listItems: [
        "1960s — Sundial Motel opens on Vaseaux Lake",
        "1970s — Nostalgic lake-holiday atmosphere",
        "Generations — Families return year after year",
        "Today — Eight private cabin-style units in the historic building",
      ],
      images: [img("historic", "Sundial Motel era placeholder")],
      ctaText: "Read our story",
      ctaUrl: "/about",
    },
    {
      sectionKey: "activities",
      type: "custom",
      enabled: true,
      order: 6,
      eyebrow: "Lake days",
      heading: "Fishing, swimming, paddling, wildlife, and quiet evenings",
      listItems: [
        "Fishing",
        "Swimming",
        "Boating",
        "Kayaking & paddleboarding",
        "Wildlife watching",
        "Evening gatherings",
        "Stargazing",
      ],
      images: demoGallery(3, "Lake activities"),
      metadata: { layout: "activity-constellation" },
    },
    {
      sectionKey: "unit-includes",
      type: "rich-text",
      enabled: true,
      order: 7,
      eyebrow: "Every unit",
      heading: "What every unit includes",
      listItems: SHARED_AMENITIES,
      images: demoGallery(2, "In-unit amenities"),
      backgroundImage: img("kitchen", "Cabin kitchen placeholder"),
    },
    {
      sectionKey: "packing-note",
      type: "rich-text",
      enabled: true,
      order: 8,
      eyebrow: "Essential packing",
      heading: "Bring your own bedding, towels, and toiletries",
      body: "Kitchen basics, dishes, cookware, and propane for the BBQ are provided. Guests supply bedding, towels, and personal toiletries.",
      foregroundImage: img("cabinInterior", "Cozy cabin interior"),
    },
    {
      sectionKey: "seasons",
      type: "seasons",
      enabled: true,
      order: 9,
      heading: "Seasons & stays",
      subheading:
        "Weekly high-season rentals from Canada Day week through Labour Day week. Shorter shoulder-season stays may be available in May, June, and September.",
      body: "Rates vary by guest count, duration, and dates. Contact us for availability and a quote — we do not publish fixed prices online.",
      ctaText: "Rates & seasons",
      ctaUrl: "/rates-and-seasons",
    },
    {
      sectionKey: "last-minute-cta",
      type: "cta",
      enabled: true,
      order: 10,
      heading: "Ask about last-minute openings",
      subheading: "Cancellations sometimes create short-notice availability.",
      ctaText: "Inquire now",
      ctaUrl: "/inquire?interest=last-minute",
      backgroundImage: img("lakeHero", "Last-minute lake opening"),
    },
    {
      sectionKey: "testimonials-preview",
      type: "testimonials",
      enabled: true,
      order: 11,
      heading: "Guest memories",
      subheading: "Demo testimonials are seeded for layout — replace before launch.",
      ctaText: "Read testimonials",
      ctaUrl: "/testimonials",
    },
    {
      sectionKey: "things-to-do-preview",
      type: "custom",
      enabled: true,
      order: 12,
      heading: "Things to do",
      subheading: "On the lake, in nature, and across the South Okanagan.",
      ctaText: "Explore local guide",
      ctaUrl: "/things-to-do",
      images: demoGallery(3, "Things to do preview"),
      metadata: { layout: "things-to-do-preview" },
    },
    {
      sectionKey: "faq-preview",
      type: "faq-preview",
      enabled: true,
      order: 13,
      heading: "Common questions",
      ctaText: "View all FAQs",
      ctaUrl: "/faqs",
    },
    {
      sectionKey: "final-inquiry",
      type: "cta",
      enabled: true,
      order: 14,
      heading: "Ready for lake days?",
      subheading: "Submit an inquiry — your stay is not confirmed until we reply.",
      ctaText: "Check availability",
      ctaUrl: "/inquire",
      images: demoGallery(2, "Final inquiry collage"),
    },
  ];
}

function aboutSections(): IPageSection[] {
  return [
    {
      sectionKey: "hero",
      type: "hero",
      enabled: true,
      order: 0,
      eyebrow: "Our story",
      heading: "From the Sundial Motel to summers remembered",
      subheading: "Generations of lake holidays on the shores of Vaseaux Lake.",
      backgroundImage: img("historic", "Historic Sundial Motel placeholder"),
      images: demoGallery(3, "About hero collage"),
    },
    {
      sectionKey: "brand-story",
      type: "rich-text",
      enabled: true,
      order: 1,
      heading: "A classic Okanagan lake vacation",
      body: "Originally opened as the Sundial Motel in the 1960s, our property has welcomed generations of visitors to the shores of Vaseaux Lake. Today, the original building continues to offer eight cabin-style accommodations, each with its own space and character — a little taste of the 1970s, when summer holidays meant lakeside days, family time, and making memories together.",
      images: demoGallery(2, "Brand story"),
    },
    {
      sectionKey: "memory-timeline",
      type: "timeline",
      enabled: true,
      order: 2,
      heading: "Memory timeline",
      listItems: [
        "1960s — Property opens as the Sundial Motel",
        "1970s — Nostalgic lakeside holiday atmosphere",
        "Generations — Families return for simple summer traditions",
        "Today — Eight private units within the historic building",
      ],
      images: [img("historic", "Archival lakeside memory")],
    },
    {
      sectionKey: "architectural-truth",
      type: "image-text",
      enabled: true,
      order: 3,
      eyebrow: "Architectural truth",
      heading: "Eight units, one unforgettable roofline",
      body: "The property is something more unusual than eight detached cabins: private cabin-style accommodations under one historic roof, surrounded by Eagle's Bluff, McIntyre Bluff, and the heart of Vaseaux Lake.",
      backgroundImage: img("cabinInterior", "Unit layout placeholder"),
      foregroundImage: img("lakeHero", "Lake view from property"),
    },
    {
      sectionKey: "landscape",
      type: "image-text",
      enabled: true,
      order: 4,
      eyebrow: "Between two bluffs",
      heading: "Eagle's Bluff, McIntyre Bluff, and Vaseaux Lake",
      body: "Ponderosa pines and majestic willow shade frame the property. Bighorn sheep and various bird species may be spotted nearby — wildlife is never guaranteed.",
      images: demoGallery(2, "Landscape views"),
      backgroundImage: img("nature", "Bluffs and lake landscape"),
    },
    {
      sectionKey: "values",
      type: "rich-text",
      enabled: true,
      order: 5,
      heading: "Family-friendly values",
      listItems: [
        "Simple comforts and outdoor connection",
        "Quiet evenings by the water",
        "A small, authentic property — not a large resort",
        "A community of repeat guests and returning families",
      ],
      images: [img("patioBbq", "Family values lakeside")],
    },
    {
      sectionKey: "cta",
      type: "cta",
      enabled: true,
      order: 6,
      heading: "Plan your chapter of the story",
      ctaText: "View cabins",
      ctaUrl: "/cabins",
      label: "Inquire",
      metadata: { secondaryCtaText: "Check availability", secondaryCtaUrl: "/inquire" },
    },
  ];
}

function cabinsSections(): IPageSection[] {
  return [
    {
      sectionKey: "hero",
      type: "hero",
      enabled: true,
      order: 0,
      heading: "Eight private stays. One unforgettable lakeside setting.",
      subheading:
        "Compare Cabins 5–12 by capacity, separate bedroom, and sleeping layout — then inquire for your dates.",
      backgroundImage: img("cabinInterior", "Cabins index hero"),
      images: demoGallery(3, "Cabins hero collage"),
    },
    {
      sectionKey: "layout-explanation",
      type: "rich-text",
      enabled: true,
      order: 1,
      heading: "Private units within a shared historic building",
      body: "Each cabin is a private cabin-style accommodation within our lakeside building — not a detached standalone cabin. Shared outdoor spaces, boats, and the lake are steps away.",
      images: [img("historic", "Building layout placeholder")],
    },
    {
      sectionKey: "cabin-grid",
      type: "cabin-rail",
      enabled: true,
      order: 2,
      heading: "Cabins 5–12",
      metadata: { layout: "full-grid", showFilters: true },
    },
    {
      sectionKey: "shared-amenities",
      type: "rich-text",
      enabled: true,
      order: 3,
      eyebrow: "Included in every unit",
      heading: "Shared in-unit amenities",
      listItems: SHARED_AMENITIES,
      images: demoGallery(2, "Shared amenities"),
      backgroundImage: img("kitchen", "Kitchen amenity"),
    },
    {
      sectionKey: "packing",
      type: "rich-text",
      enabled: true,
      order: 4,
      heading: "Packing checklist",
      listItems: [
        "Bedding for all guests",
        "Bath towels",
        "Toiletries",
        "Sun protection and lake gear",
      ],
      body: "Kitchen basics and propane are provided.",
      foregroundImage: img("cabinInterior", "Packing reminder"),
    },
    {
      sectionKey: "rates-teaser",
      type: "seasons",
      enabled: true,
      order: 5,
      heading: "Rates & seasons",
      body: "We do not publish fixed prices. Contact us for availability and a personalized quote.",
      ctaText: "Rates & seasons",
      ctaUrl: "/rates-and-seasons",
    },
    {
      sectionKey: "policies-teaser",
      type: "cta",
      enabled: true,
      order: 6,
      heading: "Policies & FAQs",
      subheading: "Review packing requirements and property guidelines before you arrive.",
      ctaText: "View policies",
      ctaUrl: "/policies",
      metadata: { secondaryCtaText: "FAQs", secondaryCtaUrl: "/faqs" },
    },
  ];
}

function servicesSections(): IPageSection[] {
  return [
    {
      sectionKey: "hero",
      type: "hero",
      enabled: true,
      order: 0,
      eyebrow: "Experiences",
      heading: "Stay types and lake experiences",
      subheading: "From weekly high-season holidays to quiet couples' getaways — inquire for your dates.",
      backgroundImage: img("boats", "Services hero"),
      images: demoGallery(3, "Services hero collage"),
    },
    {
      sectionKey: "intro",
      type: "rich-text",
      enabled: true,
      order: 1,
      body: "Our services describe how guests enjoy Vaseaux Lake — not resort upsells. Every stay is quoted individually based on dates, cabin, and party size.",
    },
    {
      sectionKey: "service-cards",
      type: "custom",
      enabled: true,
      order: 2,
      heading: "Ways to stay",
      metadata: { layout: "service-grid", source: "services" },
    },
    {
      sectionKey: "inquiry-how",
      type: "rich-text",
      enabled: true,
      order: 3,
      heading: "How inquiry works",
      listItems: [
        "Submit dates, guest count, and interests",
        "We review availability and prepare a quote",
        "Your stay is confirmed only when we agree together",
        "No instant online booking or payment on this site",
      ],
      images: [img("lakeHero", "Inquiry process")],
    },
    {
      sectionKey: "seasonal-note",
      type: "seasons",
      enabled: true,
      order: 4,
      heading: "Seasonal availability",
      body: "High season, shoulder months, and last-minute openings each have different rules. See Rates & Seasons for overview copy.",
      ctaText: "Rates & seasons",
      ctaUrl: "/rates-and-seasons",
    },
    {
      sectionKey: "safety-reminder",
      type: "rich-text",
      enabled: true,
      order: 5,
      heading: "Important considerations",
      body: "Lake conditions, wildlife, weather, and equipment availability vary. We do not guarantee specific experiences — share your interests when you inquire.",
    },
    {
      sectionKey: "cta",
      type: "cta",
      enabled: true,
      order: 6,
      heading: "Tell us how you want to stay",
      ctaText: "Start an inquiry",
      ctaUrl: "/inquire",
    },
  ];
}

function ratesSections(): IPageSection[] {
  return [
    {
      sectionKey: "hero",
      type: "hero",
      enabled: true,
      order: 0,
      heading: "A simple stay, quoted for your dates",
      subheading: "Contact for pricing — rates vary and are not published as fixed amounts.",
      backgroundImage: img("lakeHero", "Rates and seasons hero"),
      images: demoGallery(2, "Rates hero collage"),
    },
    {
      sectionKey: "contact-pricing",
      type: "rich-text",
      enabled: true,
      order: 1,
      heading: "Contact for pricing",
      body: "Every inquiry receives a personalized quote based on guest count, stay length, selected cabin, and dates. There is no public price table on this website.",
      quote: "Your stay is not confirmed until we reply and agree on details.",
    },
    {
      sectionKey: "high-season",
      type: "seasons",
      enabled: true,
      order: 2,
      eyebrow: "High season",
      heading: "Weekly rentals — Canada Day week through Labour Day week",
      body: "Our busiest weeks are configured annually in admin. Weekly stays are typical during this period.",
    },
    {
      sectionKey: "shoulder-season",
      type: "rich-text",
      enabled: true,
      order: 3,
      eyebrow: "Shoulder seasons",
      heading: "May, June, and September",
      body: "Shorter stays and different minimum-night rules may be available. Inquire for current shoulder-season options.",
      images: [img("nature", "Shoulder season lake")],
    },
    {
      sectionKey: "variability",
      type: "stats",
      enabled: true,
      order: 4,
      heading: "What affects your quote",
      stats: [
        { label: "Guests", value: "Adults & children" },
        { label: "Duration", value: "Nights & week alignment" },
        { label: "Cabin", value: "Capacity & layout" },
        { label: "Dates", value: "Season & demand" },
      ],
    },
    {
      sectionKey: "capacity-compare",
      type: "cabin-rail",
      enabled: true,
      order: 5,
      heading: "Cabin capacity comparison",
      metadata: { layout: "compare-capacity" },
    },
    {
      sectionKey: "includes",
      type: "rich-text",
      enabled: true,
      order: 6,
      heading: "What every stay includes",
      listItems: [
        ...SHARED_AMENITIES,
        "Access to shared lawn, beach, and lake",
        "Complimentary boats and paddleboards when available",
      ],
      images: demoGallery(2, "Stay includes"),
    },
    {
      sectionKey: "packing",
      type: "rich-text",
      enabled: true,
      order: 7,
      heading: "What guests bring",
      listItems: ["Bedding", "Towels", "Toiletries"],
    },
    {
      sectionKey: "last-minute",
      type: "cta",
      enabled: true,
      order: 8,
      heading: "Last-minute openings",
      subheading: "Ask if a cancellation has opened your preferred dates.",
      ctaText: "Inquire about openings",
      ctaUrl: "/inquire?interest=last-minute",
    },
    {
      sectionKey: "faq-cta",
      type: "faq-preview",
      enabled: true,
      order: 9,
      heading: "Rates & seasons FAQs",
      ctaText: "View FAQs",
      ctaUrl: "/faqs",
    },
  ];
}

function gallerySections(): IPageSection[] {
  return [
    {
      sectionKey: "hero",
      type: "hero",
      enabled: true,
      order: 0,
      heading: "Lake days in pictures",
      subheading: "Demo placeholders across every gallery category — replace before launch.",
      backgroundImage: img("lakeHero", "Gallery hero"),
      images: demoGallery(4, "Gallery hero mosaic"),
    },
    {
      sectionKey: "gallery-mosaic",
      type: "gallery",
      enabled: true,
      order: 1,
      heading: "Explore the property",
      metadata: { layout: "editorial-mosaic", showCategoryFilters: true },
    },
  ];
}

function testimonialsSections(): IPageSection[] {
  return [
    {
      sectionKey: "hero",
      type: "hero",
      enabled: true,
      order: 0,
      heading: "Guest memories",
      subheading: "Demo testimonials only — replace with real reviews before publishing.",
      backgroundImage: img("stars", "Testimonials hero"),
      images: demoGallery(2, "Testimonials hero collage"),
    },
    {
      sectionKey: "slider",
      type: "testimonials",
      enabled: true,
      order: 1,
      metadata: { layout: "cinematic-slider", demoOnly: true },
    },
    {
      sectionKey: "review-wall",
      type: "testimonials",
      enabled: true,
      order: 2,
      heading: "Review wall",
      metadata: { layout: "editorial-wall" },
    },
    {
      sectionKey: "repeat-guests",
      type: "rich-text",
      enabled: true,
      order: 3,
      heading: "Generations of lake holidays",
      body: "Families have returned to Vaseaux Lake for decades. Replace this section with owner-approved stories — do not invent guest counts or statistics.",
      images: [img("historic", "Repeat guests memory strip")],
    },
    {
      sectionKey: "memory-strip",
      type: "custom",
      enabled: true,
      order: 4,
      heading: "Guest-memory image strip",
      images: demoGallery(5, "Guest memory strip"),
      metadata: { layout: "film-strip" },
    },
    {
      sectionKey: "cta",
      type: "cta",
      enabled: true,
      order: 5,
      heading: "Create your own memories",
      ctaText: "Inquire",
      ctaUrl: "/inquire",
    },
  ];
}

function faqsSections(): IPageSection[] {
  return [
    {
      sectionKey: "hero",
      type: "hero",
      enabled: true,
      order: 0,
      heading: "Frequently asked questions",
      subheading: "Booking, cabins, packing, lake equipment, and policies — answered from confirmed property information.",
      backgroundImage: img("lakeHero", "FAQs hero"),
      images: demoGallery(3, "FAQs supporting images"),
    },
    {
      sectionKey: "faq-accordion",
      type: "faq-preview",
      enabled: true,
      order: 1,
      metadata: {
        layout: "searchable-accordion",
        categories: [
          "Booking",
          "Rates & Seasons",
          "Cabins",
          "Packing",
          "Lake & Equipment",
          "Families",
          "Arrival & Stay",
          "Policies",
        ],
      },
    },
    {
      sectionKey: "cta",
      type: "cta",
      enabled: true,
      order: 2,
      heading: "Still have questions?",
      ctaText: "Contact us",
      ctaUrl: "/contact",
      metadata: { secondaryCtaText: "Submit inquiry", secondaryCtaUrl: "/inquire" },
    },
  ];
}

function thingsToDoSections(): IPageSection[] {
  return [
    {
      sectionKey: "hero",
      type: "hero",
      enabled: true,
      order: 0,
      heading: "Things to do",
      subheading: "On the lake, in nature, and across the South Okanagan.",
      backgroundImage: img("nature", "Things to do hero"),
      images: demoGallery(4, "Things to do hero collage"),
    },
    {
      sectionKey: "on-property",
      type: "image-text",
      enabled: true,
      order: 1,
      eyebrow: "On property",
      heading: "Lake days without leaving home",
      listItems: [
        "Fishing",
        "Swimming",
        "Boating",
        "Paddleboards",
        "Floating raft",
        "Lawn gatherings",
        "Stargazing",
      ],
      images: demoGallery(3, "On-property activities"),
      backgroundImage: img("boats", "On-property boating"),
    },
    {
      sectionKey: "nature",
      type: "image-text",
      enabled: true,
      order: 2,
      eyebrow: "Nature",
      heading: "Pines, willows, birds, and possible bighorn sheep",
      body: "Wildlife sightings are possible but never guaranteed. Enjoy the landscape between Eagle's Bluff and McIntyre Bluff.",
      images: [img("nature", "Nature and wildlife")],
    },
    {
      sectionKey: "landscape",
      type: "rich-text",
      enabled: true,
      order: 3,
      heading: "Vaseaux Lake landscape story",
      body: "The property faces the heart of Vaseaux Lake, framed by bluffs and Okanagan sky.",
      foregroundImage: img("lakeHero", "Vaseaux Lake panorama placeholder"),
    },
    {
      sectionKey: "attractions",
      type: "custom",
      enabled: true,
      order: 4,
      heading: "Local attractions",
      subheading: "Verified on-property guides and draft placeholders for owner-reviewed listings.",
      metadata: {
        layout: "attraction-grid",
        categories: ["Nature", "Food & Wine", "Family", "Scenic Drives", "Day Trips"],
      },
    },
  ];
}

function contactSections(): IPageSection[] {
  return [
    {
      sectionKey: "hero",
      type: "hero",
      enabled: true,
      order: 0,
      heading: "Contact us",
      subheading: "Questions before you inquire? We are happy to help.",
      backgroundImage: img("lakeHero", "Contact hero"),
      images: demoGallery(5, "Contact film strip"),
      metadata: { layout: "film-strip-collage" },
    },
    {
      sectionKey: "contact-details",
      type: "rich-text",
      enabled: true,
      order: 1,
      heading: "Reach us directly",
      body: "Email, phone, and Facebook are managed in global Settings and appear here automatically.",
      metadata: { source: "site-settings-contact" },
    },
    {
      sectionKey: "contact-form",
      type: "custom",
      enabled: true,
      order: 2,
      heading: "Send a message",
      metadata: { layout: "contact-form" },
    },
  ];
}

function policiesSections(): IPageSection[] {
  return [
    {
      sectionKey: "hero",
      type: "hero",
      enabled: true,
      order: 0,
      heading: "Property policies",
      subheading: "Confirmed packing requirements and placeholders pending owner review.",
      backgroundImage: img("cabinInterior", "Policies hero"),
    },
    {
      sectionKey: "policy-intro",
      type: "rich-text",
      enabled: true,
      order: 1,
      body: "Only the bedding/towels/toiletries requirement is confirmed at seed time. All other policy sections are clearly marked placeholders and must be reviewed before launch.",
      listItems: policyListItems(),
    },
    {
      sectionKey: "policy-details",
      type: "rich-text",
      enabled: true,
      order: 2,
      heading: "Policy details",
      body: policySectionsBody(),
      metadata: { policies: policyListItems() },
    },
    {
      sectionKey: "cta",
      type: "cta",
      enabled: true,
      order: 3,
      heading: "Questions about policies?",
      ctaText: "Contact us",
      ctaUrl: "/contact",
    },
  ];
}

export const pageSeeds = [
  {
    slug: "home",
    title: "Home",
    status: "published" as const,
    sections: homeSections(),
    seo: {
      title: "Vaseaux Lake Rentals | Waterfront Cabins",
      description:
        "Family-friendly cabin-style accommodations on Vaseaux Lake in the South Okanagan. Inquire for availability and a quote.",
      ogImage: img("lakeHero", "Vaseaux Lake open graph image"),
    },
    isArchived: false,
  },
  {
    slug: "about",
    title: "About",
    status: "published" as const,
    sections: aboutSections(),
    seo: {
      title: "About | Vaseaux Lake Waterfront Cabins",
      description:
        "From the Sundial Motel to today's lakeside cabins — generations of Okanagan summer memories.",
      ogImage: img("historic", "About page social image"),
    },
    isArchived: false,
  },
  {
    slug: "cabins",
    title: "Cabins",
    status: "published" as const,
    sections: cabinsSections(),
    seo: {
      title: "Cabins 5–12 | Vaseaux Lake Waterfront Cabins",
      description: "Compare eight private cabin-style units by capacity and sleeping layout.",
      ogImage: img("cabinInterior", "Cabins page social image"),
    },
    isArchived: false,
  },
  {
    slug: "services",
    title: "Services / Experiences",
    status: "published" as const,
    sections: servicesSections(),
    seo: {
      title: "Experiences | Vaseaux Lake Waterfront Cabins",
      description: "Weekly stays, family getaways, fishing, paddling, and more — inquire for your dates.",
      ogImage: img("boats", "Services page social image"),
    },
    isArchived: false,
  },
  {
    slug: "rates-and-seasons",
    title: "Rates & Seasons",
    status: "published" as const,
    sections: ratesSections(),
    seo: {
      title: "Rates & Seasons | Vaseaux Lake Waterfront Cabins",
      description: "High season, shoulder months, and inquiry-based pricing — contact for a quote.",
      ogImage: img("lakeHero", "Rates and seasons social image"),
    },
    isArchived: false,
  },
  {
    slug: "gallery",
    title: "Gallery",
    status: "published" as const,
    sections: gallerySections(),
    seo: {
      title: "Gallery | Vaseaux Lake Waterfront Cabins",
      description: "Lake, property, cabins, and family days — demo gallery placeholders.",
      ogImage: img("lakeHero", "Gallery social image"),
    },
    isArchived: false,
  },
  {
    slug: "testimonials",
    title: "Testimonials",
    status: "published" as const,
    sections: testimonialsSections(),
    seo: {
      title: "Testimonials | Vaseaux Lake Waterfront Cabins",
      description: "Guest memories — demo content seeded for layout testing.",
      ogImage: img("stars", "Testimonials social image"),
      noIndex: false,
    },
    isArchived: false,
  },
  {
    slug: "faqs",
    title: "FAQs",
    status: "published" as const,
    sections: faqsSections(),
    seo: {
      title: "FAQs | Vaseaux Lake Waterfront Cabins",
      description: "Answers about booking, cabins, packing, and lake stays.",
      ogImage: img("lakeHero", "FAQs social image"),
    },
    isArchived: false,
  },
  {
    slug: "things-to-do",
    title: "Things to Do",
    status: "published" as const,
    sections: thingsToDoSections(),
    seo: {
      title: "Things to Do | Vaseaux Lake Waterfront Cabins",
      description: "On-property lake days and South Okanagan exploration.",
      ogImage: img("nature", "Things to do social image"),
    },
    isArchived: false,
  },
  {
    slug: "contact",
    title: "Contact",
    status: "published" as const,
    sections: contactSections(),
    seo: {
      title: "Contact | Vaseaux Lake Waterfront Cabins",
      description: "Email, phone, and message form for Vaseaux Lake inquiries.",
      ogImage: img("lakeHero", "Contact social image"),
    },
    isArchived: false,
  },
  {
    slug: "policies",
    title: "Policies",
    status: "published" as const,
    sections: policiesSections(),
    seo: {
      title: "Policies | Vaseaux Lake Waterfront Cabins",
      description: "Property policies including confirmed packing requirements.",
      ogImage: img("cabinInterior", "Policies social image"),
    },
    isArchived: false,
  },
];
